### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sentriz**
( ͡° ͜ʖ ͡°)

### CODE REVIEW

**Comment by byxor** [comment]
As funny as this may be, I refuse to accept it.

**Comment by devoxel** [comment]
here's a real gif

https://asciinema.org/a/Uiw6xucAbsmOcIHQWE0pjTeXn

**Comment by sentriz** [comment]
ok fixed :(

**Comment by devoxel** [comment]
Merge plz

**Comment by sentriz** [comment]
agree

**Pull request merged**
